apiVersion: v1
kind: Namespace
metadata:
  name: nodejs-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: nodejs-app
  name: nodejs-app
  namespace: nodejs-app
spec:
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - image: abhidevdocker/node-web-app
        name: node-web-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-app
  name: nodejs-app
  namespace: nodejs-app
spec:
  ports:
  - nodePort: 32001
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: nodejs-app
  type: NodePort
